---
title: "Low emittance electron beam generation from a laser wakefield accelerator using two laser pulses with different wavelengths"
collection: publications
category: manuscripts
authorship: "co-author"
permalink: /publication/2014-prab-two-color-injection
excerpt: 'Novel two-color laser scheme separating wakefield excitation from injection process enables generation of ultralow emittance electron beams with more than one order of magnitude improvement.'
date: 2014-06-13
venue: 'Physical Review Special Topics - Accelerators and Beams'
paperurl: 'https://doi.org/10.1103/PhysRevSTAB.17.061301'
citation: 'Xinlu Xu, Yipeng Wu, Chaojie Zhang, Fei Li, Yang Wan, Jianfei Hua, Chi-Hao Pai, Wei Lu, Peicheng Yu, Chan Joshi, Warren B. Mori, "Low emittance electron beam generation from a laser wakefield accelerator using two laser pulses with different wavelengths," <i>Phys. Rev. ST Accel. Beams</i> 17, 061301 (2014).'
---
**Abstract:** Ionization injection triggered by short wavelength laser pulses inside a nonlinear wakefield driven by a longer wavelength laser is examined via multidimensional particle-in-cell simulations. We find that very bright electron beams can be generated through this two-color scheme in either collinear propagating or transverse colliding geometry. For a fixed laser intensity I, lasers with longer/shorter wavelength λ have larger/smaller ponderomotive potential (∝ Iλ²). The two-color scheme utilizes this property to separate the injection process from the wakefield excitation process. Very strong wakes can be generated at relatively low laser intensities by using a longer wavelength laser driver (e.g., a 10 μm CO₂ laser) due to its very large ponderomotive potential. On the other hand, short wavelength laser can produce electrons with very small residual momenta (p⊥ ∼ a₀ ∼ √I λ) inside the wake, leading to electron beams with very small normalized emittances (tens of nanometers). Using particle-in-cell simulations we show that a ~10 fs electron beam with ~4 pC of charge and a normalized emittance of ~50 nm can be generated by combining a 10 μm driving laser with a 400 nm injection laser, which is an improvement of more than one order of magnitude compared to the typical results obtained when a single wavelength laser is used for both the wake formation and ionization injection.
